// GENERATED by `npm run glsl:gen` (tools/glsl/ts2glsl.ts) from the TypeScript functions named below.
// Do not edit: change the TypeScript and regenerate. glslGenerated.test.ts fails when this file is stale.

/**
 * Pure scalar functions shared by the CPU tracer and the shaders, transpiled from their TypeScript source.
 *
 * lus-sim (decisión 49; adaptado de EchoTwin, origen y commit en docs/PROVENANCE.md): el archivo generado tal como sale de
 * `glsl:gen` en el origen, sin las funciones que no son del corazón (la distancia al mediastino del tórax de EchoTwin y las de la
 * acústica de su imagen). lus-sim no regenera este texto (ts2glsl no está portado, decisión 8): la e2e de equivalencia
 * TS ↔ GLSL es su juez.
 */
export const GLSL_GENERATED = /* glsl */ `
// src/simulator/anatomy/valveSkirt.ts: et_annulusOffset
float et_annulusOffset(float phi, float saddlePhi, float saddle, float tiltC, float tiltS, float lift) {
  float sn = sin(phi - saddlePhi);
  return saddle * (sn * sn - 0.5) + tiltC * cos(phi) + tiltS * sin(phi) + lift;
}
// src/simulator/anatomy/valveSkirt.ts: et_tvInflowTaper
float et_tvInflowTaper(float h, float close, float bulge) {
  if (h < -close) {
    return 2.0 * (-h - close);
  }
  if (h <= 0.0) {
    return 0.0;
  }
  float past = max(0.0, h - 1.6);
  return -bulge * min(1.0, h / 0.8) + 0.25 * past + 0.25 * past * past;
}
// src/simulator/anatomy/valveSkirt.ts: et_tvShortening
float et_tvShortening(float contraction, float rvRadialScale) {
  return et_TV_SYSTOLIC_SHORTENING * contraction * min(1.0, rvRadialScale);
}
// src/simulator/anatomy/lvShape.ts: et_ellipseFactor
float et_ellipseFactor(float ratio, float az) {
  float c = cos(az);
  float s = sin(az) / ratio;
  return 1.0 / sqrt(c * c + s * s);
}
// src/simulator/anatomy/lvShape.ts: et_axialWallFactor
float et_axialWallFactor(float zeta, float apexFrac) {
  if (zeta <= 0.5) {
    return 1.0;
  }
  float u = min(1.0, (zeta - 0.5) / 0.5);
  return 1.0 - (1.0 - apexFrac) * u * u;
}
// src/simulator/anatomy/lvShape.ts: et_lvNeckWeight
float et_lvNeckWeight(float zeta) {
  if (zeta >= et_LV_NECK_ZETA) {
    return 0.0;
  }
  if (zeta <= 0.0) {
    return 1.0;
  }
  float u = 1.0 - zeta / et_LV_NECK_ZETA;
  return u * u;
}
// src/simulator/anatomy/rv.ts: et_rvAxialTaper
float et_rvAxialTaper(float tvPlane, float zApex, float z) {
  if (z <= tvPlane) {
    float a = min(1.0, (tvPlane - z) / 1.5);
    return 1.0 - 0.15 * a * a * (3.0 - 2.0 * a);
  }
  float q = min(1.0, (z - tvPlane) / max(0.5, zApex - tvPlane));
  float s = max(0.0, (q - 0.25) / 0.75);
  return (1.0 - 0.55 * s) * sqrt(max(0.0, 1.0 - s * s * s * s * s));
}
// src/simulator/anatomy/rv.ts: et_rvAzProfile
float et_rvAzProfile(float rvAzA, float rvAzP, float u) {
  float sn = sin(et_PI * u);
  float uIn = (et_PI + 0.04 - rvAzA) / (rvAzP - rvAzA);
  float inflow = exp(-((u - uIn) * (u - uIn)) / (2.0 * 0.18 * 0.18));
  return pow(min(1.0, max(0.0, sn) / 0.75), 0.7) * (0.85 + 0.15 * inflow);
}
// src/simulator/anatomy/rv.ts: et_rvFloorZ
float et_rvFloorZ(float tvCz, float tvZ, float pvZ, float u, float off) {
  float uInf = 0.35;
  if (u >= uInf) {
    return tvCz + tvZ + off;
  }
  float w = u / uInf;
  return tvCz + pvZ + (tvZ + off - pvZ) * w - 2.6 * (1.0 - w);
}
// src/simulator/anatomy/rv.ts: et_rvRadialContraction
float et_rvRadialContraction(float u) {
  float s = min(1.0, max(0.0, (u - 0.15) / 0.35));
  return 0.15 + (et_RV_BODY_RADIAL_CONTRACTION - 0.15) * s * s * (3.0 - 2.0 * s);
}
// src/simulator/anatomy/rv.ts: et_rvRadialState
float et_rvRadialState(float tvZ, float tapseCm, float contraction) {
  return tapseCm > 0.0 ? min(contraction, max(0.0, tvZ / tapseCm)) : contraction;
}
// src/simulator/anatomy/rv.ts: et_rvHingeWeight
float et_rvHingeWeight(float dAz, float halfAz, float h) {
  float a = min(1.0, max(0.0, (halfAz + et_RV_HINGE_FADE_RAD - dAz) / et_RV_HINGE_FADE_RAD));
  float g = min(1.0, max(0.0, (h - et_RV_HINGE_PLATEAU_CM) / et_RV_HINGE_CM));
  return a * a * (3.0 - 2.0 * a) * (1.0 - g * g * (3.0 - 2.0 * g));
}
// src/simulator/anatomy/rv.ts: et_rvHingeRadius
float et_rvHingeRadius(float rc, float R, float dAz) {
  float sn = rc * sin(dAz);
  return rc * cos(dAz) + sqrt(max(0.0, R * R - sn * sn));
}
// src/simulator/anatomy/rv.ts: et_rvInflowSlack
float et_rvInflowSlack(float h) {
  return 1.5 * max(0.0, et_RV_INFLOW_REACH_CM - h);
}
// src/simulator/anatomy/lvWall.ts: et_septalShiftAt
float et_septalShiftAt(float shiftCm, float az, float levelFrac) {
  if (shiftCm <= 0.0) {
    return 0.0;
  }
  float c = -cos(az);
  if (c <= 0.0) {
    return 0.0;
  }
  float zw = 1.0 - (((levelFrac - 0.45) / 0.45) * ((levelFrac - 0.45) / 0.45));
  if (zw <= 0.0) {
    return 0.0;
  }
  return shiftCm * c * c * zw;
}
// src/simulator/anatomy/lvWall.ts: et_septalCrestFactor
float et_septalCrestFactor(float az, float zRel) {
  float da = abs(az - et_SEPTAL_CREST_AZ);
  if (da > et_PI) {
    da = 2.0 * et_PI - da;
  }
  if (da >= et_SEPTAL_CREST_HALF_WIDTH) {
    return 1.0;
  }
  float cw = cos((da / et_SEPTAL_CREST_HALF_WIDTH) * (et_PI / 2.0));
  float d = zRel - et_SEPTAL_CREST_Z_CM;
  float f = 1.0;
  if (d <= 0.0) {
    f = 0.2;
  } else {
    if (d < 0.1) {
      f = 0.2 + 1.1 * d;
    } else {
      if (d < 0.2) {
        f = 0.31 + 1.2 * (d - 0.1);
      } else {
        if (d < 0.5) {
          f = 0.43 + 0.7 * (d - 0.2);
        } else {
          if (d < 1.0) {
            f = 0.64 + 0.72 * (d - 0.5);
          }
        }
      }
    }
  }
  return 1.0 - cw * cw * (1.0 - f);
}
// src/simulator/anatomy/lvSegments.ts: et_lvSegmentCode
float et_lvSegmentCode(float azimuthRad, float levelFrac, float rvAzA, float rvAzP) {
  float septal = (rvAzA + rvAzP) * 0.5;
  float raw = ((azimuthRad - septal) * 180.0) / et_PI + 180.0;
  float deg = raw - 360.0 * floor(raw / 360.0);
  if (deg >= 360.0) {
    deg = 0.0;
  }
  float quadrant = 15.0;
  if (deg < 45.0 || deg >= 315.0) {
    quadrant = 16.0;
  } else {
    if (deg < 135.0) {
      quadrant = 13.0;
    } else {
      if (deg < 225.0) {
        quadrant = 14.0;
      }
    }
  }
  if (levelFrac >= 1.0) {
    return quadrant + 4.0;
  }
  if (levelFrac >= 2.0 / 3.0) {
    return quadrant;
  }
  float base = levelFrac < 1.0 / 3.0 ? 0.0 : 6.0;
  if (deg < 60.0) {
    return base + 6.0;
  }
  if (deg < 120.0) {
    return base + 1.0;
  }
  if (deg < 180.0) {
    return base + 2.0;
  }
  if (deg < 240.0) {
    return base + 3.0;
  }
  if (deg < 300.0) {
    return base + 4.0;
  }
  return base + 5.0;
}
// src/simulator/anatomy/lvSegments.ts: et_lvWallKind
float et_lvWallKind(float code) {
  float c = code >= 17.0 ? code - 4.0 : code;
  if (c == 2.0 || c == 3.0 || c == 8.0 || c == 9.0 || c == 14.0) {
    return 1.0;
  }
  if (c == 1.0 || c == 7.0 || c == 13.0) {
    return 2.0;
  }
  if (c == 4.0 || c == 5.0 || c == 10.0 || c == 11.0 || c == 15.0) {
    return 3.0;
  }
  return 0.0;
}
// src/simulator/anatomy/classify/root.ts: et_rootBend
float et_rootBend(float t) {
  return t > 3.0 ? 0.16 * (t - 3.0) * (t - 3.0) : 0.0;
}
// src/simulator/anatomy/classify/atria.ts: et_atrialScale
float et_atrialScale(float booster, float reservoir, float contraction) {
  return booster * (reservoir + (1.0 - reservoir) * contraction);
}
// src/simulator/anatomy/classify/atria.ts: et_iasThickness
float et_iasThickness(float fo) {
  return fo < 1.0 ? 0.12 : fo < 1.3 ? 0.7 : 0.55;
}
// src/simulator/anatomy/classify/atria.ts: et_raCollapseScale
float et_raCollapseScale(float raCollapse) {
  return 1.0 - 0.35 * raCollapse;
}
// src/simulator/anatomy/classify/pericardium.ts: et_effusionAt
float et_effusionAt(float eff, float dLa, float dRest) {
  float w = min(1.0, max(0.0, (dRest - dLa) / et_OBLIQUE_SINUS_TAPER_CM));
  float thin = min(eff, et_OBLIQUE_SINUS_EFFUSION_CM);
  return eff - (eff - thin) * w * w * (3.0 - 2.0 * w);
}
// src/simulator/anatomy/classify/pericardium.ts: et_posteriorColumnDistance
float et_posteriorColumnDistance(float x, float y, float z, float ux, float uy, float uz, float ax, float ay, float az, float sx, float sy, float sz) {
  float dax = x - ax;
  float day = y - ay;
  float daz = z - az;
  float ta = dax * ux + day * uy + daz * uz;
  float dA = sqrt(max(0.0, dax * dax + day * day + daz * daz - ta * ta)) - et_DESC_AORTA_MAX_OUTER_R;
  float dsx = x - sx;
  float dsy = y - sy;
  float dsz = z - sz;
  float ts = dsx * ux + dsy * uy + dsz * uz;
  float dS = sqrt(max(0.0, dsx * dsx + dsy * dsy + dsz * dsz - ts * ts)) - et_SPINE_R;
  return min(dA, dS);
}
// src/simulator/anatomy/classify/rightVentricle.ts: et_rvFreeWallNow
float et_rvFreeWallNow(float freeWallCm, float contraction) {
  return freeWallCm * (1.0 + 0.35 * contraction);
}
// src/simulator/anatomy/classify/rightVentricle.ts: et_rvOutflowScale
float et_rvOutflowScale(float contraction) {
  return 0.85 + 0.15 * (1.0 - contraction);
}
`;

/** Shader constants the generated functions read (must be #defines or constants of the including shader). */
export const GLSL_GENERATED_FREE_IDENTIFIERS: readonly string[] = ["DESC_AORTA_MAX_OUTER_R","LV_NECK_ZETA","OBLIQUE_SINUS_EFFUSION_CM","OBLIQUE_SINUS_TAPER_CM","RV_BODY_RADIAL_CONTRACTION","RV_HINGE_CM","RV_HINGE_FADE_RAD","RV_HINGE_PLATEAU_CM","RV_INFLOW_REACH_CM","SEPTAL_CREST_AZ","SEPTAL_CREST_HALF_WIDTH","SEPTAL_CREST_Z_CM","SPINE_R","TV_SYSTOLIC_SHORTENING"];
