/**
 * Limitaciones conocidas del modelo, con identificador (práctica de VExUS). Cada id debe aparecer entre
 * acentos graves en docs/LIMITATIONS.md (docs.test.ts lo exige), de modo que «lo sabíamos» sea comprobable por
 * máquina. Cuando una limitación se resuelve, se borra de aquí y del documento en el mismo cambio. Las que se
 * heredan de VExUS con el código portado conservan su identificador (decisiones 10 y 11).
 */
export const KNOWN_LIMITATIONS: ReadonlySet<string> = new Set([
  'normal-acquisition-only',
  'navigator-parametric',
  // anatomía y fisiología
  'left-handed-anatomy-frame',
  'thorax-cylindrical-cage',
  'rib-section-uniform',
  'apex-cupola-wall',
  'wall-cupola-transition',
  'supraclavicular-fossa-model',
  'subclavian-vessels-short',
  'clavicle-section-uniform',
  'anterior-rib-shape',
  'scapula-plate',
  'spine-arch-slab',
  'patient-position-anatomy',
  'arms-raised-anatomy',
  'chest-wall-regional-approx',
  'chest-wall-height-transition',
  'wall-generic-layers',
  'heart-simplified',
  'lung-border-table',
  'abdomen-generic-tissue',
  'liver-spleen-simplified',
  'stomach-traube-lens',
  'kidney-retroperitoneum-port',
  'hilum-vessels-blind-ends',
  'sliding-linear-height',
  'respiratory-field-vertical',
  'hf-single-filling-pressure',
  'hf-partial-calibration',
  'hf-truth-sweep',
  'hf-protocol-sites',
  // sonda
  'convex-probe-only',
  'probe-compression-kinematic',
  'probe-compression-in-plane',
  'operator-hand-rigid',
  // imagen
  'no-lung-comet-tails',
  'blines-no-frequency-selectivity',
  'blines-water-only',
  'blines-look0-only',
  'blines-drawn-width',
  'blines-static-ringdown',
  'blines-gcnr-saturated',
  'blines-detector-static',
  'blines-gain-range',
  'pleura-series-same-line',
  'interface-echo-coherent-only',
  'rib-acoustics-simplified',
  'rib-core-leak-center',
  'speckle-statistics-uncalibrated',
  'display-uncalibrated',
  'gpu-timer-unverified',
  'sector-detector-symmetric',
  'no-sidelobes',
  'harmonic-simplified',
]);
